Repository remindmodel/remind, pull requests merged in 2023-11, with the labels that each got.

#1473 fix @limitations goxygen tag in 50_damages/BurkeLike documentation
  modules/50_damages/BurkeLike/realization.gms
Labels: bug

#1471 introduce cm_CESMkup_ind_data for better control over industry CES markup costs
  config/scenario_config.csv
  config/scenario_config_21_EU11_ARIADNE.csv
  config/scenario_config_GCS.csv
  config/scenario_config_SHAPE.csv
  main.gms
  modules/37_industry/fixed_shares/datainput.gms
  modules/37_industry/fixed_shares/declarations.gms
  modules/37_industry/subsectors/datainput.gms
  modules/37_industry/subsectors/declarations.gms
Labels: enhancement

#1154 CDR cleaning session
  core/declarations.gms
  core/sets.gms
  main.gms
  modules/33_CDR/DAC/bounds.gms
  modules/33_CDR/DAC/datainput.gms
  modules/33_CDR/DAC/declarations.gms
  modules/33_CDR/DAC/equations.gms
  modules/33_CDR/DAC/not_used.txt
  modules/33_CDR/DAC/realization.gms
  modules/33_CDR/DAC/sets.gms
  modules/33_CDR/all/bounds.gms
  modules/33_CDR/all/declarations.gms
  modules/33_CDR/all/equations.gms
  modules/33_CDR/all/not_used.txt
  modules/33_CDR/all/realization.gms
  modules/33_CDR/all/sets.gms
  modules/33_CDR/module.gms
  modules/33_CDR/off/bounds.gms
  modules/33_CDR/off/declarations.gms
  modules/33_CDR/off/not_used.txt
  modules/33_CDR/off/realization.gms
  modules/33_CDR/portfolio/bounds.gms
  modules/33_CDR/portfolio/datainput.gms
  modules/33_CDR/portfolio/declarations.gms
  modules/33_CDR/portfolio/equations.gms
  modules/33_CDR/portfolio/input/files
  modules/33_CDR/portfolio/input/p33_transport_costs.inc
  modules/33_CDR/portfolio/realization.gms
  modules/33_CDR/portfolio/sets.gms
  modules/33_CDR/weathering/bounds.gms
  modules/33_CDR/weathering/datainput.gms
  modules/33_CDR/weathering/declarations.gms
  modules/33_CDR/weathering/equations.gms
  modules/33_CDR/weathering/input/files
  modules/33_CDR/weathering/input/p33_transport_costs.inc
  modules/33_CDR/weathering/not_used.txt
  modules/33_CDR/weathering/realization.gms
  modules/33_CDR/weathering/sets.gms
  scripts/start/prepare.R
Labels: documentation, code cleaning
